# Generated by Django 5.1.5 on 2025-01-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_students_mob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
    ]
