# Generated by Django 5.1.5 on 2025-01-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_fees_duefees_fees_paidfees_fees_totalfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='dueFees',
        ),
    ]
