# Generated by Django 5.1.5 on 2025-01-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_fees_duefees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='paidFees',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='totalFees',
        ),
    ]
