# Generated by Django 5.1.5 on 2025-01-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_fees_paidfees_remove_fees_totalfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='std',
        ),
    ]
