# Generated by Django 5.1.5 on 2025-01-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_delete_attendence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_01', models.CharField(max_length=2)),
                ('date_02', models.CharField(max_length=2)),
                ('date_03', models.CharField(max_length=2)),
                ('date_04', models.CharField(max_length=2)),
                ('date_05', models.CharField(max_length=2)),
                ('date_06', models.CharField(max_length=2)),
                ('date_07', models.CharField(max_length=2)),
                ('date_08', models.CharField(max_length=2)),
                ('date_09', models.CharField(max_length=2)),
                ('date_10', models.CharField(max_length=2)),
                ('date_11', models.CharField(max_length=2)),
                ('date_12', models.CharField(max_length=2)),
                ('date_13', models.CharField(max_length=2)),
                ('date_14', models.CharField(max_length=2)),
                ('date_15', models.CharField(max_length=2)),
                ('date_16', models.CharField(max_length=2)),
                ('date_17', models.CharField(max_length=2)),
                ('date_18', models.CharField(max_length=2)),
                ('date_19', models.CharField(max_length=2)),
                ('date_20', models.CharField(max_length=2)),
                ('date_21', models.CharField(max_length=2)),
                ('date_22', models.CharField(max_length=2)),
                ('date_23', models.CharField(max_length=2)),
                ('date_24', models.CharField(max_length=2)),
                ('date_25', models.CharField(max_length=2)),
                ('date_26', models.CharField(max_length=2)),
                ('date_27', models.CharField(max_length=2)),
                ('date_28', models.CharField(max_length=2)),
                ('date_29', models.CharField(max_length=2)),
                ('date_30', models.CharField(max_length=2)),
                ('date_31', models.CharField(max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
