# Generated by Django 5.1.5 on 2025-01-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_studentattendence_delete_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAttendence',
        ),
    ]
