# Generated by Django 5.1.5 on 2025-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='totalFees',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
