# Generated by Django 5.1.5 on 2025-01-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='dueFees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='paidFees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='totalFees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='testDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='obtainedMarks',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='totalMarks',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_01',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_02',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_03',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_04',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_05',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_06',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_07',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_08',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_09',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_10',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_11',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_12',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_13',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_14',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_15',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_16',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_17',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_18',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_19',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_20',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_21',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_22',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_23',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_24',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_25',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_26',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_27',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_28',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_29',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_30',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='date_31',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
