# Generated by Django 5.1.5 on 2025-01-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_fees_duefees_fees_paidfees_fees_totalfees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fees',
        ),
    ]
