# Generated by Django 5.1.5 on 2025-01-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentattendence',
            name='user',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
        migrations.DeleteModel(
            name='fees',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='StudentAttendence',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
