# Generated by Django 5.1.5 on 2025-01-19 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0032_remove_marks_user_remove_studentattendence_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('totalFees', models.IntegerField(blank=True, null=True)),
                ('paidFees', models.IntegerField(blank=True, null=True)),
                ('dueFees', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('testDate', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=10, null=True)),
                ('totalMarks', models.IntegerField(blank=True, max_length=10, null=True)),
                ('obtainedMarks', models.IntegerField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_01', models.CharField(blank=True, max_length=2, null=True)),
                ('date_02', models.CharField(blank=True, max_length=2, null=True)),
                ('date_03', models.CharField(blank=True, max_length=2, null=True)),
                ('date_04', models.CharField(blank=True, max_length=2, null=True)),
                ('date_05', models.CharField(blank=True, max_length=2, null=True)),
                ('date_06', models.CharField(blank=True, max_length=2, null=True)),
                ('date_07', models.CharField(blank=True, max_length=2, null=True)),
                ('date_08', models.CharField(blank=True, max_length=2, null=True)),
                ('date_09', models.CharField(blank=True, max_length=2, null=True)),
                ('date_10', models.CharField(blank=True, max_length=2, null=True)),
                ('date_11', models.CharField(blank=True, max_length=2, null=True)),
                ('date_12', models.CharField(blank=True, max_length=2, null=True)),
                ('date_13', models.CharField(blank=True, max_length=2, null=True)),
                ('date_14', models.CharField(blank=True, max_length=2, null=True)),
                ('date_15', models.CharField(blank=True, max_length=2, null=True)),
                ('date_16', models.CharField(blank=True, max_length=2, null=True)),
                ('date_17', models.CharField(blank=True, max_length=2, null=True)),
                ('date_18', models.CharField(blank=True, max_length=2, null=True)),
                ('date_19', models.CharField(blank=True, max_length=2, null=True)),
                ('date_20', models.CharField(blank=True, max_length=2, null=True)),
                ('date_21', models.CharField(blank=True, max_length=2, null=True)),
                ('date_22', models.CharField(blank=True, max_length=2, null=True)),
                ('date_23', models.CharField(blank=True, max_length=2, null=True)),
                ('date_24', models.CharField(blank=True, max_length=2, null=True)),
                ('date_25', models.CharField(blank=True, max_length=2, null=True)),
                ('date_26', models.CharField(blank=True, max_length=2, null=True)),
                ('date_27', models.CharField(blank=True, max_length=2, null=True)),
                ('date_28', models.CharField(blank=True, max_length=2, null=True)),
                ('date_29', models.CharField(blank=True, max_length=2, null=True)),
                ('date_30', models.CharField(blank=True, max_length=2, null=True)),
                ('date_31', models.CharField(blank=True, max_length=2, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('mob', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
