# Generated by Django 5.1.5 on 2025-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField(blank=True, max_length=3, null=True)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('chaptername', models.CharField(blank=True, max_length=20, null=True)),
                ('notesFile', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
