# Generated by Django 5.1.5 on 2025-01-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_students_std'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAttandance',
            fields=[
                ('studentattendence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.studentattendence')),
            ],
            bases=('app1.studentattendence',),
        ),
    ]
