# Generated by Django 5.1.5 on 2025-01-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_newattandance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fees',
        ),
    ]
