# Generated by Django 5.1.5 on 2025-02-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
